# Site settings
title: Viraat Aryabumi
description: Viraat Aryabumi - IT student | Photographer | Developer
baseurl: "" 
url: "http://www.varuponyou.in"
root: /
keywords: Viraat Aryabumi personal website blog travel food hike design programming

# Build settings
markdown: kramdown
permalink: /:title