# Site settings
title: Thoughts
header-img: img/home-bg.jpg
email: viraat94@gmail.com
description: "A place where I share my thoughts about all things life"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: viraat7
github_username:  var7
facebook_username:  viraat94

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
