name: Be.
description: Viraat Aryabumi's blog

url: viraataryabumi.in
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: viraataryabumi.info